package constants

const AwsFunctionPlatform = "AWS Lambda"
const AwsDefaultRegion = "AWS_DEFAULT_REGION"
const ThundraLambdaDebugEnable = "thundra_lambda_debug_enable"
const AwsLambdaInvocationRequestId = "aws.lambda.invocation.request_id"
const AwsLambdaInvocationRequest = "aws.lambda.invocation.request"
const AwsLambdaInvocationResponse = "aws.lambda.invocation.response"
const AwsLambdaARN = "aws.lambda.arn"
const AwsLambdaInvocationColdStart = "aws.lambda.invocation.coldstart"
const AwsLambdaInvocationTimeout = "aws.lambda.invocation.timeout"
const AwsLambdaLogGroupName = "aws.lambda.log_group_name"
const AwsLambdaLogStreamName = "aws.lambda.log_stream_name"
const AwsLambdaMemoryLimit = "aws.lambda.memory_limit"
const AwsLambdaName = "aws.lambda.name"
const AwsRegion = "aws.region"
const AwsError = "error"
const AwsErrorKind = "error.kind"
const AwsErrorMessage = "error.message"
const AwsErrorStack = "error.stack"
