package constants

const ApplicationPlatform = "AWS Lambda"
const AwsDefaultRegion = "AWS_DEFAULT_REGION"
const ThundraLambdaDebugEnable = "thundra_lambda_debug_enable"
const AwsLambdaInvocationRequestId = "aws.lambda.invocation.request_id"
const AwsLambdaInvocationRequest = "aws.lambda.invocation.request"
const AwsLambdaInvocationResponse = "aws.lambda.invocation.response"
const AwsLambdaARN = "aws.lambda.arn"
const AwsAccountNo = "aws.account_no"
const AwsLambdaInvocationColdStart = "aws.lambda.invocation.coldstart"
const AwsLambdaInvocationTimeout = "aws.lambda.invocation.timeout"
const AwsLambdaLogGroupName = "aws.lambda.log_group_name"
const AwsLambdaLogStreamName = "aws.lambda.log_stream_name"
const AwsLambdaMemoryLimit = "aws.lambda.memory_limit"
const AwsLambdaMemoryUsage = "aws.lambda.invocation.memory_usage"
const AwsLambdaName = "aws.lambda.name"
const AwsRegion = "aws.region"
const AwsError = "error"
const AwsErrorKind = "error.kind"
const AwsErrorMessage = "error.message"
const AwsErrorStack = "error.stack"
const AwsLambdaApplicationDomain = "API"
const AwsLambdaApplicationClass = "AWS-Lambda"

const AwsLambdaTriggerOperationName = "x-thundra-trigger-operation-name"
const AwsLambdaTriggerDomainName = "x-thundra-trigger-domain-name"
const AwsLambdaTriggerClassName = "x-thundra-trigger-class-name"
const AwsLambdaTriggerResourceName = "x-thundra-resource-name"

const AwsLambdaFunctionMemorySize = "AWS_LAMBDA_FUNCTION_MEMORY_SIZE"
const AwsLambdaRegion = "AWS_REGION"

const AwsXRayTraceHeader = "_X_AMZN_TRACE_ID"
const AwsXRayTraceContextKey = "x-amzn-trace-id"
const AwsXRaySegmentID = "aws.xray.segment.id"
const AwsXRayTraceID = "aws.xray.trace.id"
